export type actionTypes = {
  FETCH_FILMS_REQUEST?: 'FETCH_FILMS_REQUEST';
  FETCH_FILMS_STARTED?: 'FETCH_FILMS_STARTED';
  FETCH_FILMS_SUCCEEDED?: 'FETCH_FILMS_SUCCEEDED';
  FETCH_FILMS_FAILED?: 'FETCH_FILMS_FAILED';

  FETCH_PEOPLE_REQUEST?: 'FETCH_PEOPLE_REQUEST';
  FETCH_PEOPLE_STARTED?: 'FETCH_PEOPLE_STARTED';
  FETCH_PEOPLE_SUCCEEDED?: 'FETCH_PEOPLE_SUCCEEDED';
  FETCH_PEOPLE_FAILED?: 'FETCH_PEOPLE_FAILED';

  FETCH_PLANETS_REQUEST?: 'FETCH_PLANETS_REQUEST';
  FETCH_PLANETS_STARTED?: 'FETCH_PLANETS_STARTED';
  FETCH_PLANETS_SUCCEEDED?: 'FETCH_PLANETS_SUCCEEDED';
  FETCH_PLANETS_FAILED?: 'FETCH_PLANETS_FAILED';

  FETCH_SPECIES_REQUEST?: 'FETCH_SPECIES_REQUEST';
  FETCH_SPECIES_STARTED?: 'FETCH_SPECIES_STARTED';
  FETCH_SPECIES_SUCCEEDED?: 'FETCH_SPECIES_SUCCEEDED';
  FETCH_SPECIES_FAILED?: 'FETCH_SPECIES_FAILED';

  FETCH_STARSHIPS_REQUEST?: 'FETCH_STARSHIPS_REQUEST';
  FETCH_STARSHIPS_STARTED?: 'FETCH_STARSHIPS_STARTED';
  FETCH_STARSHIPS_SUCCEEDED?: 'FETCH_STARSHIPS_SUCCEEDED';
  FETCH_STARSHIPS_FAILED?: 'FETCH_STARSHIPS_FAILED';

  FETCH_VEHICLES_REQUEST?: 'FETCH_VEHICLES_REQUEST';
  FETCH_VEHICLES_STARTED?: 'FETCH_VEHICLES_STARTED';
  FETCH_VEHICLES_SUCCEEDED?: 'FETCH_VEHICLES_SUCCEEDED';
  FETCH_VEHICLES_FAILED?: 'FETCH_VEHICLES_FAILED';
};
